name: Build and Deploy (MYKS)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies (Legacy Mode)
        run: |
          npm install --legacy-peer-deps
          npm install react-toastify --legacy-peer-deps
          npm install postcss-cli tailwindcss autoprefixer --legacy-peer-deps
          npm install lucide-react jspdf-autotable --legacy-peer-deps
          # Inisialisasi konfigurasi Tailwind (abaikan error jika sudah ada)
          npx tailwindcss init -p || true

      - name: Build Project
        run: npm run build

      # Jika kamu menggunakan deployment ke Vercel:
      - name: Deploy to Vercel (Legacy)
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
